### PR TITLE
Update BaseResponse.php to support response generation

### PR DESCRIPTION
**Pull request by JanjacVD**

### CODE REVIEW

**Comment by JanjacVD** [comment]
image
image
@hussein4alaa I aborted my previos PR, here are the new changes with fiexes, screenshots for proof :)

**Comment by hussein4alaa** [comment]
Screenshot 2024-09-17 at 11 19 29 PM

**Comment by JanjacVD** [comment]
@hussein4alaa  Try it out now

**Comment by hussein4alaa** [comment]
@JanjacVD Thank you, you did a great job.

**Pull request closed without merging**
